<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 C:\Users\Liempo\Documents\Development\driftrunner.web.app\static\models\R34.glb --root /models/ --types --printwidth 120 --precision 2
Author: LePoint_BAT (https://sketchfab.com/LePointBAT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-japan-nissan-skyline-r34-30c3e10eeed64f30b65786bc3ca9cbdb
Title: TOON Japan : Nissan Skyline R34
-->

<script lang="ts">
	import * as THREE from 'three'
	import {
		T,
		type Props,
		type Events,
		type Slots,
		forwardEventHandlers
	} from '@threlte/core'
	import { useGltf, type ThrelteGltf } from '@threlte/extras'

	type $$Props = Props<THREE.Group> & CarProps
	type $$Events = Events<THREE.Group>
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	type CarProps = {
		paintColor?: THREE.ColorRepresentation
		rimsColor?: THREE.ColorRepresentation
	}

	export const ref = new THREE.Group()

	type GLTFResult = {
		nodes: {
			Object_14: THREE.Mesh
			Object_15: THREE.Mesh
			Object_16: THREE.Mesh
			Object_17: THREE.Mesh
			Object_18: THREE.Mesh
			Object_20: THREE.Mesh
			Object_21: THREE.Mesh
			Object_22: THREE.Mesh
			Object_23: THREE.Mesh
			Object_25: THREE.Mesh
			Object_26: THREE.Mesh
			Object_27: THREE.Mesh
			Object_28: THREE.Mesh
			Object_4: THREE.Mesh
			Object_5: THREE.Mesh
			Object_6: THREE.Mesh
			Object_7: THREE.Mesh
			Object_8: THREE.Mesh
			Object_9: THREE.Mesh
			Object_10: THREE.Mesh
			Object_11: THREE.Mesh
			Object_12: THREE.Mesh
		}
		materials: {
			Caliper: THREE.MeshStandardMaterial
			Rims: THREE.MeshStandardMaterial
			Tire: THREE.MeshStandardMaterial
			Black: THREE.MeshStandardMaterial
			Disk: THREE.MeshStandardMaterial
			Chrome: THREE.MeshStandardMaterial
			Paint: THREE.MeshStandardMaterial
			Red_Lights: THREE.MeshStandardMaterial
			White_Lights: THREE.MeshStandardMaterial
			Interior: THREE.MeshStandardMaterial
			Windows: THREE.MeshStandardMaterial
			Licence_Plate: THREE.MeshStandardMaterial
		}
	}

	const gltf = useGltf<GLTFResult>('/models/R34.glb')

	const createShaderOutline = (thickness: number) =>
		new THREE.ShaderMaterial({
			vertexShader: /* glsl */ `
							void main() {
								vec3 newPosition = position + normal * ${thickness};
								gl_Position = projectionMatrix * modelViewMatrix * vec4(newPosition, 1.0);
							}
						`,
			fragmentShader: /* glsl */ `
							void main() {
								gl_FragColor = vec4(0, 0, 0, 1);
							}
						`,
			side: THREE.BackSide
		})

	const gradientMap = new THREE.TextureLoader().load('/textures/fivetone.jpg')
	gradientMap.minFilter = THREE.NearestFilter
	gradientMap.magFilter = THREE.NearestFilter
	const toMeshToolMaterial = (
		color: THREE.ColorRepresentation
	): THREE.MeshToonMaterial => {
		return new THREE.MeshToonMaterial({
			color: color,
			gradientMap: gradientMap
		})
	}

	const component = forwardEventHandlers()
</script>

<T
	is={ref}
	dispose={false}
	{...$$restProps}
	bind:this={$component}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[-0.38, 0.15, -0.64]}>
			<T.Mesh
				geometry={gltf.nodes.Object_14.geometry}
				material={gltf.materials.Caliper}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_15.geometry}
				material={toMeshToolMaterial(
					$$props.rimsColor || gltf.materials.Rims.color
				)}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_16.geometry}
				material={gltf.materials.Tire}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_17.geometry}
				material={gltf.materials.Black}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_18.geometry}
				material={gltf.materials.Disk}
			/>
		</T.Group>
		<T.Group position={[0.33, 0.15, -0.63]}>
			<T.Mesh
				geometry={gltf.nodes.Object_20.geometry}
				material={gltf.materials.Caliper}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_21.geometry}
				material={toMeshToolMaterial(
					$$props.rimsColor || gltf.materials.Rims.color
				)}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_22.geometry}
				material={gltf.materials.Tire}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_23.geometry}
				material={gltf.materials.Disk}
			/>
		</T.Group>
		<T.Group position={[-0.02, 0.15, 0.5]}>
			<T.Mesh
				geometry={gltf.nodes.Object_25.geometry}
				material={gltf.materials.Caliper}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_26.geometry}
				material={toMeshToolMaterial(
					$$props.rimsColor || gltf.materials.Rims.color
				)}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_27.geometry}
				material={gltf.materials.Tire}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_28.geometry}
				material={gltf.materials.Disk}
			/>
		</T.Group>
		<T.Mesh
			geometry={gltf.nodes.Object_4.geometry}
			material={gltf.materials.Caliper}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_4.geometry}
			material={toMeshToolMaterial(
				$$props.rimsColor || gltf.materials.Rims.color
			)}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_5.geometry}
			material={gltf.materials.Black}
		/>

		<T.Mesh
			geometry={gltf.nodes.Object_6.geometry}
			material={gltf.materials.Chrome}
		/>

		<T.Mesh
			geometry={gltf.nodes.Object_7.geometry}
			material={toMeshToolMaterial(
				$$props.paintColor || gltf.materials.Paint.color
			)}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_7.geometry}
			material={createShaderOutline(0.017)}
		/>

		<T.Mesh
			geometry={gltf.nodes.Object_8.geometry}
			material={gltf.materials.Red_Lights}
		/>

		<T.Mesh
			geometry={gltf.nodes.Object_9.geometry}
			material={gltf.materials.White_Lights}
		/>

		<T.Mesh
			geometry={gltf.nodes.Object_10.geometry}
			material={gltf.materials.Interior}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_11.geometry}
			material={gltf.materials.Windows}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_12.geometry}
			material={gltf.materials.Licence_Plate}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
